# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 16:26
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pomodoro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField(default=datetime.datetime(2017, 4, 22, 16, 25, 58, 604629, tzinfo=utc))),
                ('is_canceled', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pomodoros', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('started',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='pomodoro',
            unique_together=set([('user', 'started')]),
        ),
    ]
