# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 17:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170422_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pomodoro',
            name='started',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 22, 17, 23, 47, 138382, tzinfo=utc)),
        ),
    ]
