# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 08:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170423_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pomodoro',
            name='started',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 23, 8, 17, 46, 114141, tzinfo=utc)),
        ),
    ]
